apiVersion: v1
kind: Pod
metadata:
  name: config-map-test2
spec:
  containers:
    - name: config-map-use2
      image: alpine
      command: ["sleep", "3600"]

      volumeMounts:
        - mountPath: "/entireConfigMap"
          name: config
          readOnly: true
      imagePullPolicy: IfNotPresent

  restartPolicy: Always
  volumes:
    - name: config
      # 不使用items指定具体key, 二十挂载整个configMap
      configMap:
        # 提供你想要挂载的 ConfigMap 的名字
        name: game-demo
