apiVersion: v1
kind: Pod
metadata:
  name: downward-api-test2
spec:
  containers:
    - name: client-container
      image: alpine
      command: ["sh", "-c"]
      args:
        # 循环cat /etc/podinfo/, 通过kubectl logs可以查看到输出
        - while true; do
          echo -en '\n';
          if [[ -e /etc/podinfo/cpu_limit ]]; then
          echo -en '\n'; cat /etc/podinfo/cpu_limit; fi;
          if [[ -e /etc/podinfo/cpu_request ]]; then
          echo -en '\n'; cat /etc/podinfo/cpu_request; fi;
          if [[ -e /etc/podinfo/mem_limit ]]; then
          echo -en '\n'; cat /etc/podinfo/mem_limit; fi;
          if [[ -e /etc/podinfo/mem_request ]]; then
          echo -en '\n'; cat /etc/podinfo/mem_request; fi;
          sleep 5;
          done;

      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"

      volumeMounts:
        - mountPath: /etc/podinfo/
          name: podinfo
          readOnly: false
      imagePullPolicy: IfNotPresent
  restartPolicy: Always

  # 使用downwardAPI将容器的resources.requests/limits挂载到容器的/etc/podinfo/
  volumes:
    - name: podinfo
      projected:
        sources:
          - downwardAPI:
              items:
                - path: "cpu_limit"
                  resourceFieldRef:
                    containerName: client-container
                    resource: limits.cpu
                    divisor: 1m
                - path: "cpu_request"
                  resourceFieldRef:
                    containerName: client-container
                    resource: requests.cpu
                    divisor: 1m
                - path: "mem_limit"
                  resourceFieldRef:
                    containerName: client-container
                    resource: limits.memory
                    divisor: 1Mi
                - path: "mem_request"
                  resourceFieldRef:
                    containerName: client-container
                    resource: requests.memory
                    divisor: 1Mi

#[root@master pod]# kubectl exec -it downward-api-test2 -- /bin/sh

#/ # cat /etc/podinfo/cpu_request
#125/ #

#/ # cat /etc/podinfo/mem_request
#32/ #

#/ # cat /etc/podinfo/mem_limit
#64/ #

#/ # cat /etc/podinfo/cpu_limit
#250/ #