apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
# 非透明：需要base64编码
type: Opaque
data:
  # [root@node1 docker]# echo root | base64
  # cm9vdAo=
  # [root@node1 docker]# echo 123456 | base64
  # MTIzNDU2Cg==
  user: cm9vdAo=
  pwd: MTIzNDU2Cg==
