apiVersion: v1
kind: Pod
metadata:
  name: test-project-volume
spec:
  containers:
    - name: test-secret-volume
      image: alpine
      args:
        - sleep
        - "86400"
      volumeMounts:
        - mountPath: "/projectVolume"
          name: mysql-credential
          readOnly: true
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  volumes:
    - name: mysql-credential
      # project类型volume
      projected:
        # project volume数据源: secret
        sources:
          - secret:
              # secret对象名称
              name: mysql-secret

