apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      name: web
  # clusterIP：None，即：这个 Service，没有一个 VIP 作为“头”
  clusterIP: None
