apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels:
    app: nginx
spec:
  replicas: 2
  # 比deployment, 多了一个 serviceName字段
  serviceName: nginx-headless
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www
#      restartPolicy: Always
  volumeClaimTemplates:
   - metadata:
        name: www
     spec:
       accessModes:
         - ReadWriteOnce
       resources:
         requests:
           storage: 1Gi

